# Generated by Django 4.1.1 on 2022-09-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0002_pontaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontaj',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pontaj',
            name='start_date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
