# Generated by Django 4.1.1 on 2022-10-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0004_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
